service: som-qualtrics-survey-responses
variablesResolutionMode: 20210326
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-west-2
  memorySize: 256
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-west-2:324125712306:secret:som/qualtrics/api_key-iVmbWI"

    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : SOMQualtricsSurveyResponseBucket
            - "/*"
  environment:
    BUCKET: ${self:custom.outputBucket}
    QUALTRICS_API_TOKEN: ${self:custom.qualtricsApiToken.SOM_QUALTRICS_API_TOKEN}
    QUALTRICS_DATA_CENTER: "ucsf.co1"

custom:
  outputBucket: 'som-qualtrics-survey-responses-${opt:stage, self:provider.stage}'
  qualtricsApiToken: ${ssm:/aws/reference/secretsmanager/som/qualtrics/api_key}

functions:
  storeSurveys:
    timeout: 600
    handler: handler.storeSurveys
    events:
      - schedule: rate(30 minutes)
    environment:
      SURVEY_IDS: > 
        SV_exInb81a5EtSLDT,
        SV_a5a70rQTMniNw1g,
        SV_6DmwctPCjjgHYBo,
        SV_79CfnLzV6eLGUWW,
        SV_bK7vU2Zk1WzBOBf,
        SV_d6UsHGihbYWM4sd,
        SV_3mlSFVpWmhXC245,
        SV_3wqXbUWZxfFQ7bL,
        SV_8Bt9BEvMDp8ADWt,
        SV_40fxH6k2D56Jmyp,
        SV_0jOtXZ54ynJGOMZ,
        SV_0SQhsikeG2St445,
        SV_4UVvdY2oDgOm6Db,
        SV_7WzPjUZlr4YSrPL,
        SV_0GrS0vnQVLrbAz3,
        SV_aY4PCQzC5slzfHD,
        SV_bO6jl8AOueiS0PX,
        SV_2498foz7l1fSGlD,
        SV_0Ncvxstu2pxlCPb,
        SV_9ZDwhVZDlflCXVb,
        SV_3OuwCxLQDMIPXgh,
        SV_0pvpV6isPLivSvz,
        SV_9mord1xXTlsdQJT,
        SV_9AXy9LNoKeX8bzf,
        SV_3yEl2wErmkQFgd7,
        SV_ac0zqC6911Dlhnn,
        SV_eetprYZHPYsbvdr,
        SV_1ZIhWLiKI83av6l,
        SV_79UU4XxA3XxtuZv,
        SV_789tk1Z80fVs6VL,
        SV_bmjIgWxCoZBrSWF,
        SV_3a61vB0hhXcouJD,
        SV_8xhF6joSf7OxJ53,
        SV_6R1yfS417x7IaDr,
        SV_01bc1bjaoJpZO8B,
        SV_0NFOF7vOrjvpWHr,
        SV_0onopRpXydzpcB7,
        SV_0VwcaXHEvY4mXRP,
        SV_9SK60Ufpgk2Q7KR,
        SV_6u2pmFnEefzieep,
        SV_1ZmBQXHQI7ux9Zj,
        SV_0v6enn1osXBYfjf,
        SV_6tm3h70xK8GWPOZ,
        SV_3RcB75IJDyR03LT,
        SV_do6asCXH95beNUN,
        SV_0e0bOcqp0LVezvD,
        SV_afykIZuRuxuWkId,
        SV_bJmcqD98FQ8ateJ,
        SV_bvE9BsTsQ4qrP7L,
        SV_6PV2C7YezYaJc5n,
        SV_bjtMvLAlqR2Sh3D,
        SV_39osWSDC6uEyvSR,
        SV_5mOSza7cZe4HbGR,
        SV_0V63P2llk6kuwPb,
        SV_9Ytv0DgNEy9taAJ,
        SV_abFO7KohjhulO7Q,
        SV_6VEqKiZOjcuJ5pI,
        SV_eJONoZyl22RTQ7I,
        SV_d5SG31YfRtk7wqi,
        SV_1FXmmR3v67xmn4O,
        SV_5zQWbH7kOkjY8n4,
        SV_eLt4b4VUVsOHo8K,
        SV_6YlA8XsPVUhuCdD,
        SV_a3txY1fmRTMoPel,
        SV_07YN5dueqP7G1jE,
        SV_9YaJc8Bm3oPjZvU,
        SV_0AG1efP3AaOUGMd,
        SV_5tY7GW0vrVVg3k2,
        SV_4I2tFtjn2SKS4rs,
        SV_5nVznH4lNXdoupM,
        SV_d3Z8EKEIU7auZGS,
        SV_baoeGgFjsrIh2QK,
        SV_dhbV5NjglUWfQJ8,
        SV_eURUM5rOXOes52m,
        SV_ai5KlA9xHzZyZaC,
        SV_ea1LuAiQO9iwP7E


# you can add CloudFormation resource templates here
resources:
 Resources:
   SOMQualtricsSurveyResponseBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${self:custom.outputBucket}
       PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
       BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
