name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '52 5 * * 6' # weekly, on Saturday morning

jobs:
  test:
    name: Lint Only (No Tests)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: install dependencies
      run: npm ci
    - name: test
      run: npm test
