name: Tag Version

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.ZORGBORT_TOKEN }}
    - name: Setup Git
      run: |
        git config user.name Zorgbort
        git config user.email info@iliosproject.org
    - name: Increment Version
      run: npm version major
    - name: Push Changes
      run: git push --follow-tags