name: Tag Version

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.ZORGBORT_TOKEN }}
    - name: Setup Git
      run: |
        git config user.name Zorgbort
        git config user.email info@iliosproject.org
    - name: Increment Version
      run: npm version major
    - name: Push Changes
      run: git push --follow-tags
    - name: Notify Slack on Failure - Ilios deployment channel
      uses: act10ns/slack@v2
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ILIOS_DEPLOYMENT_WEBHOOK_URL }}
      with:
        status: ${{ job.status }}
        message: Version Tagging Failed {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }}
